on:
  push:
    branches:
      - "main"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - id: build-publish
        uses: bitovi/github-actions-storybook-to-github-pages@v1.0.4
        with:
          path: storybook-static
        env:
          RANSOM_TEXT_ASSET_URL: ${{ vars.RANSOM_TEXT_ASSET_URL }}
